(()=>{"use strict";
const KEY="jee-mastery-v5",Q=s=>document.querySelector(s),A=s=>[...document.querySelectorAll(s)],esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),today=()=>new Date().toISOString().slice(0,10);
let S=JSON.parse(localStorage.getItem(KEY)||"null")||{onboarded:false,name:"",year:"",hours:"",days:7,wake:"",start:"",sleep:"",mode:"",target:"",theme:"light",tasks:[],subjects:[],tests:[],sessions:{},mistakes:[]};
let timer={sec:1500,on:false,id:null};const save=()=>localStorage.setItem(KEY,JSON.stringify(S)),toast=x=>{Q("#toast").textContent=x;Q("#toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>Q("#toast").classList.remove("show"),1800)},mins=()=>Object.values(S.sessions).reduce((a,b)=>a+Number(b||0),0),streak=()=>{let n=0,d=new Date;for(;;){let k=d.toISOString().slice(0,10);if(!S.sessions[k])break;n++;d.setDate(d.getDate()-1)}return n},mastery=()=>{let x=S.subjects.flatMap(s=>s.chapters||[]).flatMap(c=>c.topics||[]).map(t=>+t.progress||0);return x.length?Math.round(x.reduce((a,b)=>a+b,0)/x.length):0},pct=s=>{let x=(s.chapters||[]).flatMap(c=>c.topics||[]).map(t=>+t.progress||0);return x.length?Math.round(x.reduce((a,b)=>a+b,0)/x.length):0};
function view(v){let map={today:["TODAY","Your desk"],plan:["PLANNING","Your week"],curriculum:["CURRICULUM","Build your syllabus"],tests:["PERFORMANCE","Your tests"],review:["REVIEW","Read the signals"],settings:["PROFILE","Your setup"]};A(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));Q("#sectionKicker").textContent=map[v][0];Q("#sectionTitle").textContent=map[v][1];Q("#content").dataset.view=v;render(v);Q(".sidebar")?.classList.remove("open")}
A(".nav").forEach(b=>b.onclick=e=>{e.preventDefault();go(b.dataset.view)});Q("#mobileMenu").onclick=()=>Q(".sidebar").classList.toggle("open");Q("#profile").onclick=()=>view("settings");Q("#modeBtn").onclick=()=>{S.theme=S.theme==="dark"?"light":"dark";save();render()};Q("#quickAdd").onclick=()=>addTask();Q("#command").onclick=()=>{Q("#palette").classList.remove("hidden");Q("#paletteInput").focus();commands("")};Q("#palette").onclick=e=>{if(e.target.id==="palette")Q("#palette").classList.add("hidden")};Q("#paletteInput").oninput=e=>commands(e.target.value);
function commands(q){let a=[["Today","today"],["Plan","plan"],["Curriculum","curriculum"],["Tests","tests"],["Review","review"],["Setup","settings"],["Add task","add"]].filter(x=>x[0].toLowerCase().includes(q.toLowerCase()));Q("#paletteList").innerHTML=a.map(x=>'<button class="cmd" data-c="'+x[1]+'">'+x[0]+"</button>").join("");A("[data-c]").forEach(b=>b.onclick=()=>{Q("#palette").classList.add("hidden");b.dataset.c==="add"?addTask():view(b.dataset.c)})}
function empty(title,text,action,label){return '<div class="empty"><b style="display:block;color:var(--ink);font:700 16px Manrope;margin-bottom:6px">'+title+"</b>"+text+(action?'<br><button class="primary" data-action="'+action+'" style="margin-top:12px">'+label+" →</button>":"")+"</div>"}
function render(v){document.body.classList.toggle("dark",S.theme==="dark");Q("#profile").textContent=(S.name||"S")[0].toUpperCase();({today:todayView,plan:planView,curriculum:curriculumView,tests:testsView,review:reviewView,settings:settingsView}[v]||todayView)()}
function todayView(){let m=S.sessions[today()]||0,target=+S.hours*60||0,p=target?Math.min(100,Math.round(m/target*100)):0,next=S.tasks.find(t=>!t.done);Q("#content").innerHTML='<div class="hero"><div><span class="eyebrow">JEE MASTERY / TODAY</span><h1>'+(S.name?"Welcome back, "+esc(S.name)+".":"Your preparation starts here.")+'<br><i>'+(S.year?"JEE "+esc(S.year)+".":"Make it yours.")+'</i></h1><p>'+(S.hours?"You planned "+esc(S.hours)+" focused hours today. Start with the work that matters most.":"Set your exam year and daily study commitment. The workspace will adapt around them.")+'</p></div><div class="hero-side"><span>CONSISTENCY</span><strong>'+streak()+'</strong><span>days with logged focus</span></div></div><div class="grid"><section class="card dark-card focus"><span class="eyebrow">NEXT ACTION</span><h2>'+(next?esc(next.name):"Nothing scheduled yet.")+'</h2><p>'+(next?esc(next.meta||""): "JEE Mastery will not invent your syllabus or goals. Add the work you actually want to do.")+'</p><div class="actions"><button class="primary" id="startFocus">Start 25 min focus →</button><button class="secondary" data-action="task">Add task</button></div></section><section class="card"><span class="eyebrow">FOCUS CLOCK</span><div class="timer" id="timer">'+String(Math.floor(timer.sec/60)).padStart(2,"0")+":"+String(timer.sec%60).padStart(2,"0")+'</div><small class="muted">A simple distraction-free session.</small><div class="actions"><button class="primary" id="timerBtn">'+(timer.on?"Pause":"Start")+'</button><button class="secondary" id="timerReset">Reset</button></div></section></div><div class="metrics"><div class="metric"><small>TODAY</small><b>'+Math.floor(m/60)+"h "+m%60+"m</b></div><div class="metric"><small>DAILY COMMITMENT</small><b>'+(S.hours?S.hours+"h":"—")+'</b></div><div class="metric"><small>CURRICULUM</small><b>'+S.subjects.length+" subjects</b></div><div class="metric"><small>MASTERY</small><b>"+mastery()+"%</b></div></div><div class="section"><div class="section-head"><div><span class="eyebrow">YOUR WORK</span><h2>Next actions</h2></div><button data-action="task">+ Add</button></div>'+(S.tasks.length?'<div class="list">'+S.tasks.map(t=>'<div class="row '+(t.done?"done":"")+'"><button class="check" data-task="'+t.id+'">✓</button><div><b>'+esc(t.name)+'</b><small>'+esc(t.meta||"")+'</small></div><span class="pill">'+esc(t.tag||"STUDY")+"</span></div>").join("")+"</div>":empty("A clean start.","Add the work you want to see here.","task","Add your first task"))+"</div>";bind();Q("#startFocus").onclick=startTimer;Q("#timerBtn").onclick=toggleTimer;Q("#timerReset").onclick=resetTimer}
function planView(){let d=new Date,start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));let days=Array.from({length:7},(_,i)=>{let x=new Date(start);x.setDate(start.getDate()+i);return x});Q("#content").innerHTML='<div class="page-title"><span class="eyebrow">PLANNING / YOUR RHYTHM</span><h1>Your week.</h1><p>Plan around your real availability. Nothing is pre-scheduled for you.</p></div><div class="week">'+days.map(x=>'<button type="button" data-plan-date="'+x.toISOString().slice(0,10)+'" class="day '+(x.toISOString().slice(0,10)===activePlanDate?"active":"")+'"><b>'+x.toLocaleDateString("en",{weekday:"short"}).toUpperCase()+"</b><small>"+x.getDate()+"</small></button>").join("")+'</div><div class="two"><section><div class="section-head"><div><span class="eyebrow">TASKS</span><h2>Planned work</h2></div><button data-action="task">+ Add</button></div><div class="schedule">'+(S.tasks.length?S.tasks.map(t=>'<div class="schedule-row"><span class="time">'+esc(t.time||"—")+'</span><div><b>'+esc(t.name)+'</b><small>'+esc(t.meta||"")+'</small></div><span class="pill">'+(t.done?"DONE":esc(t.tag||"STUDY"))+"</span></div>").join(""):empty("Your plan is blank.","That is intentional. Add your own study blocks.","task","Add work"))+'</div></section><aside class="card"><span class="eyebrow">YOUR COMMITMENT</span><h2>'+(S.hours||"—")+' <small class="muted">hours/day</small></h2><p>'+((S.days||7)+" study days/week")+'</p><button class="secondary" data-view-settings>Adjust setup</button></aside></div>';bind();Q("[data-view-settings]").onclick=()=>view("settings")}
function curriculumView(){let s=S.subjects.find(x=>x.id===activeSubjectId)||S.subjects[0];activeSubjectId=s?.id||null;Q("#content").innerHTML='<div class="page-title"><span class="eyebrow">CURRICULUM / BUILDER</span><h1>Your syllabus.</h1><p>Create the structure you actually follow: subjects → chapters → topics. No pre-filled JEE content.</p></div><div class="studio"><aside class="subject-menu">'+S.subjects.map((x,i)=>'<button class="'+(x.id===activeSubjectId?"active":"")+'" data-subject="'+x.id+'">'+esc(x.name)+" · "+pct(x)+"%</button>").join("")+'<button data-action="subject">＋ Add subject</button></aside><main>'+(s?'<div class="section-head" style="margin-top:0"><div><span class="eyebrow">SUBJECT</span><h2>'+esc(s.name)+'</h2></div><button data-action="chapter" data-s="'+s.id+'">+ Chapter</button></div>'+(s.chapters||[]).map(c=>'<article class="chapter"><div class="chapter-top"><b>'+esc(c.name)+'</b><span class="pill">'+(c.topics||[]).length+" topics</span></div><div class="topics">"+((c.topics||[]).map(t=>'<div class="topic"><span>'+esc(t.name)+'</span><span>'+t.progress+'%</span></div>').join("")||'<div class="topic">No topics yet</div>')+'<button class="add-link" data-action="topic" data-s="'+s.id+'" data-c="'+c.id+'">+ add topic</button></div></article>').join(""):empty("Your curriculum is empty.","Define your own subjects first.","subject","Add subject"))+'</main></div>';bind()}
function testsView(){let avg=S.tests.length?Math.round(S.tests.reduce((a,t)=>a+Number(t.score),0)/S.tests.length):0;Q("#content").innerHTML='<div class="page-title"><span class="eyebrow">PERFORMANCE / EVIDENCE</span><h1>Tests.</h1><p>Log real attempts. Let the results show where your preparation needs work.</p></div><div class="tests-grid"><section class="card stat-card"><span class="eyebrow">AVERAGE</span><h2>'+ (S.tests.length?avg+"%":"—")+'</h2><p>'+S.tests.length+" test"+(S.tests.length===1?"":"s")+" recorded.</p><button class="primary" data-action="test">Log a test →</button></section><section class="card stat-card"><span class="eyebrow">REVIEW QUEUE</span><h2>'+S.mistakes.length+'</h2><p>Mistakes captured for review.</p><button class="secondary" data-action="mistake">Capture mistake</button></section></div><div class="table">'+(S.tests.length?S.tests.slice().reverse().map(t=>'<div class="test-row"><b>'+esc(t.name)+'</b><span class="muted">'+esc(t.date||"")+'</span><strong>'+esc(t.score)+'%</strong><span class="muted">'+esc(t.percentile||"—")+'</span></div>').join(""):empty("No results yet.","Your first test becomes the baseline."))+'</div>';bind()}
function reviewView(){let m=mins(),avg=S.tests.length?Math.round(S.tests.reduce((a,t)=>a+Number(t.score),0)/S.tests.length):0;Q("#content").innerHTML='<div class="page-title"><span class="eyebrow">REVIEW / SIGNALS</span><h1>What is the work telling you?</h1><p>Review is deliberately simple: time, testing, consistency and mistakes.</p></div><div class="review-grid"><section class="card"><span class="eyebrow">FOCUS</span><h2>'+Math.floor(m/60)+"h "+m%60+"m</h2><p>Total focused time recorded on this device.</p></section><section class="card"><span class="eyebrow">TESTING</span><h2>'+(S.tests.length?avg+"%":"No baseline")+'</h2><p>Average of the tests you entered.</p></section><section class="card"><span class="eyebrow">CONSISTENCY</span><h2>'+streak()+" days</h2><p>Consecutive days with a recorded focus session.</p></section><section class="card"><span class="eyebrow">MISTAKES</span><h2>"+S.mistakes.length+"</h2><p>Capture errors while they are still understandable.</p></section></div>"}
function settingsView(){let fields=[["name","Name","text"],["year","JEE year","text"],["hours","Focused hours / day","number"],["days","Study days / week","number"],["wake","Wake time","time"],["start","Preferred study start","time"],["sleep","Sleep time","time"],["target","Target (optional)","text"]];Q("#content").innerHTML='<div class="page-title"><span class="eyebrow">PROFILE / CONTROL</span><h1>Your setup.</h1><p>These values shape the workspace. They do not create fake syllabus content or goals.</p></div><div class="settings">'+fields.map(f=>'<label class="setting"><span><b>'+f[1]+'</b><small>Saved on this device.</small></span><input class="field" data-set="'+f[0]+'" type="'+f[2]+'" value="'+esc(S[f[0]]||"")+'"></label>').join("")+'<label class="setting"><span><b>Preparation mode</b><small>How you describe your routine.</small></span><select class="field" data-set="mode"><option value="self">Self study</option><option value="coaching">Coaching + self study</option><option value="hybrid">Hybrid</option></select></label></div><div class="danger"><b>Reset all data</b><p>This removes the local JEE Mastery workspace.</p><button id="reset">Reset everything</button></div>';A("[data-set]").forEach(x=>{x.value=S[x.dataset.set]||x.value;x.onchange=()=>{S[x.dataset.set]=x.value;save();toast("Saved")}});Q("#reset").onclick=()=>{if(confirm("Reset everything?")){localStorage.removeItem(KEY);location.reload()}}}
function bind(){A("[data-action]").forEach(b=>b.onclick=()=>({task:addTask,subject:addSubject,chapter:()=>addChapter(b.dataset.s),topic:()=>addTopic(b.dataset.s,b.dataset.c),test:addTest,mistake:addMistake}[b.dataset.action]||(()=>{}))());A("[data-task]").forEach(b=>b.onclick=()=>{let t=S.tasks.find(x=>x.id===b.dataset.task);t.done=!t.done;if(t.done){S.sessions[today()]=(S.sessions[today()]||0)}save();render("today")})}
function modal(title,body,done){Q("#modalBody").innerHTML='<form class="form"><h2>'+title+'</h2>'+body+'<button class="primary">Save</button></form>';Q("#modal").classList.remove("hidden");Q("#modalBody form").onsubmit=e=>{e.preventDefault();done(new FormData(e.target));Q("#modal").classList.add("hidden");render(Q("#content").dataset.view||"today")}}
Q("#closeModal").onclick=()=>Q("#modal").classList.add("hidden");
function addTask(){modal("Add real work.",'<label>Task<input name="name" required placeholder="What will you actually study?"></label><label>Details<input name="meta" placeholder="Chapter, resource, question set…"></label><label>Time<input name="time" type="time"></label><label>Type<select name="tag"><option>STUDY</option><option>REVISION</option><option>QUESTIONS</option><option>TEST</option></select></label>',f=>{S.tasks.push({id:crypto.randomUUID(),name:f.get("name"),meta:f.get("meta"),time:f.get("time"),tag:f.get("tag"),done:false});save()})}
function addSubject(){modal("Create a subject.",'<label>Subject name<input name="name" required placeholder="Your subject"></label>',f=>{S.subjects.push({id:crypto.randomUUID(),name:f.get("name"),chapters:[]});save()})}
function addChapter(id){modal("Add a chapter.",'<label>Chapter name<input name="name" required placeholder="Your chapter"></label>',f=>{S.subjects.find(x=>x.id===id).chapters.push({id:crypto.randomUUID(),name:f.get("name"),topics:[]});save()})}
function addTopic(sid,cid){modal("Add a topic.",'<label>Topic name<input name="name" required placeholder="Your topic"></label><label>Progress %<input name="progress" type="number" min="0" max="100" value="0"></label>',f=>{let c=S.subjects.find(x=>x.id===sid).chapters.find(x=>x.id===cid);c.topics.push({id:crypto.randomUUID(),name:f.get("name"),progress:+f.get("progress")||0});save()})}
function addTest(){modal("Log a test.",'<label>Name<input name="name" required placeholder="Mock / chapter test"></label><label>Score %<input name="score" type="number" min="0" max="100" required></label><label>Date<input name="date" type="date" value="'+today()+'"></label><label>Percentile (optional)<input name="percentile"></label>',f=>{S.tests.push({name:f.get("name"),score:+f.get("score"),date:f.get("date"),percentile:f.get("percentile")});save()})}
function addMistake(){modal("Capture a mistake.",'<label>What went wrong?<textarea name="text" rows="4" required placeholder="The exact mistake…"></textarea>',f=>{S.mistakes.push({text:f.get("text"),date:today()});save()})}
function toggleTimer(){timer.on=!timer.on;if(timer.on){timer.id=setInterval(()=>{timer.sec--;let e=Q("#timer");if(e)e.textContent=String(Math.floor(timer.sec/60)).padStart(2,"0")+":"+String(timer.sec%60).padStart(2,"0");if(timer.sec<=0){clearInterval(timer.id);timer.on=false;S.sessions[today()]=(S.sessions[today()]||0)+25;save();toast("25-minute focus recorded");render("today")}},1000)}else clearInterval(timer.id);render("today")}
function startTimer(){if(!timer.on)toggleTimer()}
function resetTimer(){clearInterval(timer.id);timer={sec:1500,on:false,id:null};render("today")}
const steps=[["When are you taking JEE?","Give the workspace a destination. You can change this later.","year"],["How many focused hours can you protect?","Not ideal hours. The number you can realistically repeat.","hours"],["What does your day look like?","Give the planner your real rhythm.","routine"],["How are you preparing?","This changes labels, not your syllabus.","mode"],["What are you aiming for?","Optional. Rank, score, college — or leave it open.","target"]];
let step=0;
function intro(){let s=steps[step],body="";if(s[2]==="year")body='<input id="i1" class="big-input" inputmode="numeric" placeholder="2027" value="'+esc(S.year)+'">';if(s[2]==="hours")body='<input id="i1" class="big-input" type="number" min="0" max="24" placeholder="6" value="'+esc(S.hours)+'"><p>Focused study, not time sitting at a desk.</p>';if(s[2]==="routine")body='<div class="choices"><input id="wake" class="big-input" type="time" value="'+esc(S.wake)+'"><input id="start" class="big-input" type="time" value="'+esc(S.start)+'"><input id="sleep" class="big-input" type="time" value="'+esc(S.sleep)+'"></div><p>Wake · study start · sleep</p>';if(s[2]==="mode")body='<div class="choices">'+["self","coaching","hybrid"].map(x=>'<button class="choice '+(S.mode===x?"active":"")+'" data-mode="'+x+'"><b>'+({self:"Self study",coaching:"Coaching + self study",hybrid:"Hybrid"}[x])+'</b><small>Choose what fits you.</small></button>').join("")+'</div>';if(s[2]==="target")body='<input id="i1" class="big-input" placeholder="Optional target" value="'+esc(S.target)+'"><p>Nothing will be invented if you leave this blank.</p>';Q("#stepNo").textContent=String(step+1).padStart(2,"0")+" / 05";Q("#introContent").innerHTML='<h2>'+s[0]+'</h2><p>'+s[1]+'</p>'+body;Q("#introBack").style.visibility=step?"visible":"hidden";Q("#introNext").innerHTML=step===4?"Open my workspace <span>→</span>":"Continue <span>→</span>";A("[data-mode]").forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;save();intro()})}
function readIntro(){let k=steps[step][2];if(k==="year"||k==="hours"||k==="target")S[{year:"year",hours:"hours",target:"target"}[k]]=Q("#i1").value;if(k==="routine"){S.wake=Q("#wake").value;S.start=Q("#start").value;S.sleep=Q("#sleep").value}}
Q("#introNext").onclick=()=>{readIntro();save();if(step<4){step++;intro()}else{S.onboarded=true;save();Q("#onboarding").classList.add("hidden");Q("#app").classList.remove("hidden");view("today")}};
Q("#introBack").onclick=()=>{readIntro();if(step){step--;intro()}};Q("#skipIntro").onclick=()=>{S.onboarded=true;save();Q("#onboarding").classList.add("hidden");Q("#app").classList.remove("hidden");view("today")};

// Robust navigation layer: one delegated handler for desktop, mobile and dynamic controls.
let activeSubjectId=S.subjects[0]?.id||null;
let activePlanDate=today();
function go(v){
  if(!["today","plan","curriculum","tests","review","settings"].includes(v)) v="today";
  history.replaceState(null,"","#"+v);
  view(v);
}
document.addEventListener("click",e=>{
  const nav=e.target.closest(".nav[data-view]");
  if(nav){e.preventDefault();go(nav.dataset.view);return}
  const jump=e.target.closest("[data-jump]");
  if(jump){e.preventDefault();go(jump.dataset.jump);return}
  const subject=e.target.closest("[data-subject]");
  if(subject){activeSubjectId=subject.dataset.subject;render("curriculum");return}
  const day=e.target.closest("[data-plan-date]");
  if(day){activePlanDate=day.dataset.planDate;render("plan");return}
});
window.addEventListener("popstate",()=>go(location.hash.slice(1)||"today"));
window.addEventListener("hashchange",()=>go(location.hash.slice(1)||"today"));

if(S.onboarded){
  Q("#onboarding").classList.add("hidden");
  Q("#app").classList.remove("hidden");
  go(location.hash.slice(1)||"today");
}else intro();
})();